# PageRank
In this notebook, you'll build on your knowledge of eigenvectors and eigenvalues by exploring the GooglePageRank algorithm.

### Introduction

PageRank developed by Larry Page and Sergey Brin.
PageRank works by counting the number and quality of links to a page to determine a rough estimate of how important the website is. The underlying assumption is that more important websites are, they are more likely to receive more links from other websites.


In [1]:
#importing libraries
import numpy as np
import numpy.linalg as la

### PageRank as a linear algebra problem
For our understanding , we will be making use of the micro internet as discussed in our videos

In [2]:
#Build Link Matrix

L = np.array([[0,   1/2, 0,  0   ],
              [1/3, 0,   0,  1/2 ],
              [1/3, 0,   0,  1/2 ],
              [1/3, 1/2, 1,  0 ]])

In [3]:
#Lets setup the initial vector r,
r = 100*np.ones(4)/4   # This will set the vector with 4 enries of 1/4 X 100 each
r # Display r value 

array([25., 25., 25., 25.])

In [4]:
#Lets perform the first iteration
r = L @ r # Apply Link matrix to R
r # Show value of r

array([12.5       , 20.83333333, 20.83333333, 45.83333333])

In [10]:
#We can run again
r = L @ r 
r

array([10.41666667, 27.08333333, 27.08333333, 35.41666667])

In [11]:
r = L @ r 
r

array([13.54166667, 21.18055556, 21.18055556, 44.09722222])

In [12]:
#We can run many times using loop
r = 100*np.ones(4)/4
for i in np.arange(100) : #Repeat 100 times
    r = L@r
r

array([11.99986288, 24.00024908, 24.00024908, 39.99963896])

In [13]:
# We can run this loop untill we get the required tolerance
r = 100*np.ones(4)/4 #4 entries of 1/4 of 100
lastR = r
r = L @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = L @ r
    i += 1
    print(r)
print(str(i) + "is the number of iterations performed for convergence")
r #finally printing r

[10.41666667 27.08333333 27.08333333 35.41666667]
[13.54166667 21.18055556 21.18055556 44.09722222]
[10.59027778 26.5625     26.5625     36.28472222]
[13.28125    21.6724537  21.6724537  43.37384259]
[10.83622685 26.11400463 26.11400463 36.93576389]
[13.05700231 22.07995756 22.07995756 42.78308256]
[11.03997878 25.74387539 25.74387539 37.47227045]
[12.87193769 22.41612815 22.41612815 42.29580601]
[11.20806408 25.4385489  25.4385489  37.91483812]
[12.71927445 22.69344042 22.69344042 41.89384471]
[11.34672021 25.1866805  25.1866805  38.27991878]
[12.59334025 22.92219946 22.92219946 41.56226083]
[11.46109973 24.9789105  24.9789105  38.58107927]
[12.48945525 23.11090621 23.11090621 41.28873232]
[11.55545311 24.80751791 24.80751791 38.82951107]
[12.40375896 23.26657324 23.26657324 41.06309457]
[11.63328662 24.6661336  24.6661336  39.03444618]
[12.3330668  23.39498529 23.39498529 40.87696261]
[11.69749265 24.54950357 24.54950357 39.20350021]
[12.27475179 23.50091432 23.50091432 40.72341957]


array([11.99886079, 24.00206936, 24.00206936, 39.99700048])

In [14]:
#Lets take a new case with 6 pages

L = np.array([[0,   1/2, 1/3, 0, 0,    0 ],
              [1/3, 0,   0,   0, 1/2, 1/3],
              [1/3, 1/2, 0,   1, 0,   0 ],
              [1/3, 0,   1/3, 0, 1/2, 1/3 ],
              [0,   0,   0,   0, 0,   1/3 ],
              [0,   0,   1/3, 0, 0,   0 ]])

In [15]:
# We can run this loop untill we get the required tolerance
r = 100*np.ones(6)/6 #6 entries of 1/6 of 100
lastR = r
r = L @ r
i = 0
while la.norm(lastR - r) > 0.01: #Tolerance
    lastR = r
    r = L @ r
    i += 1
    print(r)
print(str(i) + "is the number of iterations performed for convergence")
r #finally printing r

[19.90740741  9.25925926 39.35185185 19.44444444  1.85185185 10.18518519]
[17.74691358 10.95679012 30.70987654 24.07407407  3.39506173 13.11728395]
[15.71502058 11.98559671 35.468107   22.22222222  4.37242798 10.23662551]
[17.81550069 10.83676269 33.45336077 22.65946502  3.4122085  11.82270233]
[16.5695016  11.58550526 34.01634659 22.73662551  3.94090078 11.15112026]
[17.13153483 11.21065767 34.05254534 22.54943987  3.71704009 11.3387822 ]
[16.95617728 11.34862572 33.86528032 22.69947417  3.77959407 11.35084845]
[16.96273963 11.32547228 34.02584612 22.61389905  3.78361615 11.28842677]
[17.00468485 11.30886354 33.93088173 22.65081225  3.76280892 11.34194871]
[16.96472568 11.33028231 33.9734723  22.64057622  3.78064957 11.31029391]
[16.98963192 11.31533132 33.96062594 22.63982208  3.77009797 11.32449077]
[16.9778743  11.32308988 33.96069838 22.64329853  3.77483026 11.32020865]
[16.98177773 11.32010945 33.9641349  22.64034224  3.77340288 11.32023279]
13is the number of iterations performe

array([16.98177773, 11.32010945, 33.9641349 , 22.64034224,  3.77340288,
       11.32023279])

Congratulations! You've just calculated your first PageRank!

In [16]:
#Lets assume we have a new page added and it has link to itself
Link2 = np.array([[0,   1/2, 1/3, 0, 0,   0, 0 ],
               [1/3, 0,   0,   0, 1/2, 1/3, 0 ],
               [1/3, 1/2, 0,   1, 0,   0, 0 ],
               [1/3, 0,   1/3, 0, 1/2, 1/3, 0 ],
               [0,   0,   0,   0, 0,   1/3, 0 ],
               [0,   0,   1/3, 0, 0,   0, 0 ],
               [0,   0,   0,   0, 0,   0, 1 ]])

In [17]:
# We can run this loop untill we get the required tolerance
r = 100*np.ones(7)/7 #7 entries of 1/7 of 100
lastR = r
r = Link2 @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = Link2 @ r
    i += 1
    print(r)
print(str(i) + "is the number of iterations performed for convergence")
r #finally printing r

[17.06349206  7.93650794 33.73015873 16.66666667  1.58730159  8.73015873
 14.28571429]
[15.21164021  9.39153439 26.32275132 20.63492063  2.91005291 11.24338624
 14.28571429]
[13.47001764 10.27336861 30.40123457 19.04761905  3.74779541  8.77425044
 14.28571429]
[15.27042916  9.28865373 28.67430923 19.42239859  2.92475015 10.13374486
 14.28571429]
[14.20242994  9.93043308 29.15686851 19.48853616  3.37791495  9.55810308
 14.28571429]
[14.68417271  9.60913515 29.18789601 19.32809132  3.18603436  9.71895617
 14.28571429]
[14.53386624  9.72739347 29.02738313 19.45669214  3.23965206  9.72929867
 14.28571429]
[14.53949111  9.70754767 29.16501096 19.38334204  3.24309956  9.67579438
 14.28571429]
[14.57544415  9.69331161 29.08361291 19.41498193  3.22526479  9.72167032
 14.28571429]
[14.54119344  9.71167055 29.12011912 19.40620819  3.24055677  9.69453764
 14.28571429]
[14.56254165  9.69885541 29.10910795 19.40556179  3.23151255  9.70670637
 14.28571429]
[14.55246369  9.70550561 29.10917004 19.408

array([14.55580949,  9.70295095, 29.11211563, 19.40600763,  3.23434533,
        9.70305668, 14.28571429])

Page G is taking all the traffic on the micro-internet. Once the user goes to page G, then he can’t leave that page, as the page does not have any outgoing links.
Once the user goes to page G, then he can’t leave that page, as the page does not have any outgoing links.

To correct this, we will make use of probability that user does not follow a link, but types the url to goto another website.

As discussed in Video, this will be the equation

$$ M = d \, L + \frac{1-d}{n} \, J $$
where $J$ is an $n\times n$ matrix where every element is one.


In [18]:
d = 0.5 #Try changing once we run the code
M = d*Link2 + (1-d)/7 * np.ones([7,7])

In [19]:
r = 100*np.ones(7)/7 #7 entries of 1/7 of 100
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = M @ r
    i += 1
    print(r)
print(str(i) + "is the number of iterations performed for convergence")
r #finally printing r

[14.38492063 13.29365079 22.12301587 16.66666667  8.73015873 10.51587302
 14.28571429]
[14.15343915 13.4755291  21.19708995 17.16269841  8.89550265 10.83002646
 14.28571429]
[14.04458774 13.53064374 21.45199515 17.06349206  8.94786155 10.67570547
 14.28571429]
[14.1008506  13.4998714  21.39802873 17.07520392  8.92214139 10.71818967
 14.28571429]
[14.08416311 13.5098992  21.40556872 17.07623732  8.92922209 10.70919527
 14.28571429]
[14.08792673 13.50738906 21.40581112 17.07498385  8.92772302 10.71045193
 14.28571429]
6is the number of iterations performed for convergence


array([14.08792673, 13.50738906, 21.40581112, 17.07498385,  8.92772302,
       10.71045193, 14.28571429])

In [20]:
#Testing when d = 1
d = 1 #Try changing once we run the code
M = d*Link2 + (1-d)/7 * np.ones([7,7])
r = 100*np.ones(7)/7 #7 entries of 1/7 of 100
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = M @ r
    i += 1
    print(r)
print(str(i) + "is the number of iterations performed for convergence")
r #finally printing r

[17.06349206  7.93650794 33.73015873 16.66666667  1.58730159  8.73015873
 14.28571429]
[15.21164021  9.39153439 26.32275132 20.63492063  2.91005291 11.24338624
 14.28571429]
[13.47001764 10.27336861 30.40123457 19.04761905  3.74779541  8.77425044
 14.28571429]
[15.27042916  9.28865373 28.67430923 19.42239859  2.92475015 10.13374486
 14.28571429]
[14.20242994  9.93043308 29.15686851 19.48853616  3.37791495  9.55810308
 14.28571429]
[14.68417271  9.60913515 29.18789601 19.32809132  3.18603436  9.71895617
 14.28571429]
[14.53386624  9.72739347 29.02738313 19.45669214  3.23965206  9.72929867
 14.28571429]
[14.53949111  9.70754767 29.16501096 19.38334204  3.24309956  9.67579438
 14.28571429]
[14.57544415  9.69331161 29.08361291 19.41498193  3.22526479  9.72167032
 14.28571429]
[14.54119344  9.71167055 29.12011912 19.40620819  3.24055677  9.69453764
 14.28571429]
[14.56254165  9.69885541 29.10910795 19.40556179  3.23151255  9.70670637
 14.28571429]
[14.55246369  9.70550561 29.10917004 19.408

array([14.55580949,  9.70295095, 29.11211563, 19.40600763,  3.23434533,
        9.70305668, 14.28571429])

In [21]:
#Testing when d = 0
d = 0 #Try changing once we run the code
M = d*Link2 + (1-d)/7 * np.ones([7,7])
r = 100*np.ones(7)/7 #7 entries of 1/7 of 100
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = M @ r
    i += 1
    print(r)
print(str(i) + "is the number of iterations performed for convergence")
r #finally printing r

0is the number of iterations performed for convergence


array([14.28571429, 14.28571429, 14.28571429, 14.28571429, 14.28571429,
       14.28571429, 14.28571429])

In [22]:
#When d is zero, this is the probability of visiting random page 1/7  X 100

## Assessment

In [23]:
#Test the Program with below link Matrix

L = np.array([[0,   1/3, 1/3, 0, 0,    0 ],
              [1/4, 0,   0,   0, 1/3, 1/3],
              [1/4, 1/3, 0,  0, 0,   0 ],
              [1/4, 0,   1/3, 0, 1/3, 1/3 ],
              [0,   0,   0,   1, 0,   1/3 ],
              [1/4, 1/3,   1/3, 0, 1/3,   0 ]])

In [24]:
#Build some more matrices and run the program to get deeper  understanding