# Defining Matrices 

In [1]:
import numpy as np 

x=np.array([[1,2,3],[4,5,6]])
x   # 2X3 matrix 

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
x.shape # shape of the matrix 

(2, 3)

In [3]:
np.random.randint(0,10,(2,3)) # 2X3 matrix with random values

array([[4, 1, 1],
       [8, 3, 4]])

 # Matrix Arithmetic 

In [7]:
# addition of two matrices 
np.random.seed(0) 

a=np.random.randint(1,100,(5,4)) 
b=np.random.randint(1,100,(5,4)) 
print("a:", a)

print("b:", b) 

a: [[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]]
b: [[82 38 26 78]
 [73 10 21 81]
 [70 80 48 65]
 [83 89 50 30]
 [20 20 15 40]]


In [8]:
a+b  # addition of two matrices

array([[127,  86,  91, 146],
       [141,  20, 105, 103],
       [107, 168, 119, 154],
       [172, 102, 109,  96],
       [ 60, 108,  62, 129]])

In [9]:
a-b  # subtraction of two matrices 

array([[-37,  10,  39, -10],
       [ -5,   0,  63, -59],
       [-33,   8,  23,  24],
       [  6, -76,   9,  36],
       [ 20,  68,  32,  49]])

In [10]:
a/b  # division of two matrices

array([[0.54878049, 1.26315789, 2.5       , 0.87179487],
       [0.93150685, 1.        , 4.        , 0.27160494],
       [0.52857143, 1.1       , 1.47916667, 1.36923077],
       [1.07228916, 0.14606742, 1.18      , 2.2       ],
       [2.        , 4.4       , 3.13333333, 2.225     ]])

In [15]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))

print("a:", a)
print("b:", b)

a: [[5 2]
 [5 9]]
b: [[2 2]
 [8 4]]


In [16]:
a*b  # element wise multiplication Haadamard product 

array([[10,  4],
       [40, 36]])

In [17]:
# matrix multiplication 
np.matmul(a,b) 

array([[26, 18],
       [82, 46]])

In [18]:
a @ b # matrix multiplication 

array([[26, 18],
       [82, 46]])

In [19]:
# dot product
a.dot(b) 

array([[26, 18],
       [82, 46]])

In [21]:
# Matrix  vector multiplication 
a = np.random.randint(1,10,(4,4)) 
a

array([[4, 8, 6, 6],
       [1, 2, 6, 4],
       [1, 6, 1, 2],
       [3, 5, 3, 1]])

In [22]:
b = np.arange(2,6) 
b

array([2, 3, 4, 5])

In [24]:
op_vector = a.dot(b)  
op_vector 

array([86, 52, 34, 38])

In [25]:
#Matrix Scalar multiplication 
a 

array([[4, 8, 6, 6],
       [1, 2, 6, 4],
       [1, 6, 1, 2],
       [3, 5, 3, 1]])

In [26]:
2*a 

array([[ 8, 16, 12, 12],
       [ 2,  4, 12,  8],
       [ 2, 12,  2,  4],
       [ 6, 10,  6,  2]])

# Types of Matrixes 

In [27]:
# Square matrix 
# Symmetric matrix 
# Traingular matrix
# Diagonal matrix
# Identity matrix 

In [28]:
a 

array([[4, 8, 6, 6],
       [1, 2, 6, 4],
       [1, 6, 1, 2],
       [3, 5, 3, 1]])

In [30]:
# symmetric matrix  
a=np.array([[1,2,3,4,5],[6,1,7,8,9],[10,11,1, 12,13],[14,15,16,1,17],[18,19,20,21,1]])
a  

array([[ 1,  2,  3,  4,  5],
       [ 6,  1,  7,  8,  9],
       [10, 11,  1, 12, 13],
       [14, 15, 16,  1, 17],
       [18, 19, 20, 21,  1]])

In [31]:
# Traingular matrix 
a = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
    ])
a 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
np.triu(a) # upper traingular matrix 

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

In [33]:
np.tril(a) 

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [34]:
#diagnoal matrix 
a=np.array([[1,0,0],[0,2,0],[0,0,3]]) 

In [35]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [36]:
# identity matrix 
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
# Transpose of a matrix 
a = np.random.randint(10,100,(4,2))
a

array([[68, 33],
       [69, 12],
       [72, 45],
       [77, 92]])

In [39]:
b = a.T 
b 

array([[68, 69, 72, 77],
       [33, 12, 45, 92]])

In [41]:
# determinant of a matrix 
a = np.random.randint(10,100,(4,4)) 
a

array([[90, 42, 64, 10],
       [48, 29, 56, 52],
       [66, 70, 87, 40],
       [34, 12, 13, 23]])

In [42]:
from numpy.linalg import det 
det(a) 

-2246741.999999994

In [43]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
np.linalg.matrix_rank(x) 

2