# Gram-Schmidt process

## Instructions
In this Notebook exercise we will write a function to perform the Gram-Schmidt procedure.
The Function takes a list of vectors which are non-orthonormal, and forms an orthonormal basis from this set.
Additionally, the procedure allows us to determine the dimension of the space spanned by the basis vectors, which is equal to or less than the space which the vectors sit (this happens when one of the vector set is linearly dependent) .

First, we will write a function for 4 basis vectors, and then we will generalize the concept by making use of loops to perform to any arbitrary number of vectors.

We have added the comments to explain the reason as why we have written wherever possible. Please use the Video as Reference in case you get struck while reading.
All the Best.

## Recall from Basics

### Matrices in Python
1. The structure for matrices in *numpy* is,
```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```
2. We can access the value of each element individually using,
```python
A[n, m]
```
3. To access a whole row at in a single time using,
```python
A[n]
```

4. To access a whole column at time using,
```python
A[:, m]
```
This will select the m'th column (starting at zero column).


5. We take the dot product of the vector using the @ operator.
So, To take the dot product vectors u and v, simply use the code,
```python
u @ v
```

In [77]:
# Importing from libraries
import numpy as np
import numpy.linalg as la

# We will first write the function that performs Gram-Schmidt procedure for 4 basis vectors.
# We will take this list of vectors as the columns of a matrix, X.
# We will then iterate them, one at a time and set them to be orthogonal
# to all the vectors, and then we devide it by its magnitude to find the unit vector.

def gsprocess(X) :
    Y = np.array(X, dtype=np.float_) # Create Y - copy of X, since we are altering it's values.
    # For the Zeroth column, no other vectors are present to normalize.
    # So, We just have to normalise it. I.e. divide by its modulus, or norm.
    Y[:, 0] = Y[:, 0] / la.norm(Y[:, 0])
    
    # For the first column, we need to subtract any overlap with our new zeroth vector.
    Y[:, 1] = Y[:, 1] - Y[:, 1] @ Y[:, 0] * Y[:, 0]
    
   # For the remaining value we will normalse it 
    Y[:, 1] = Y[:, 1] / la.norm(Y[:, 1])
   
    # Repeating the same steps for column 2 and column 3
    # So, for column 2, We will subtract with the zeroth vector, and overlap with first.
    
    Y[:,2] = Y[:,2] - Y[:,2] @ Y[:,0]*Y[:,0] - Y[:,2] @ Y[:,1]*Y[:,1]
    
    Y[:,2] = Y[:,2]/la.norm(Y[:,2])

    #Similar Steps for Column 3
    Y[:,3] = Y[:,3] - Y[:,3] @ Y[:,0] * Y[:,0] - Y[:,3] @ Y[:,1] * Y[:,1] - Y[: ,3] @ Y[:,2] * Y[:,2]
    
    Y[:,3] = Y[:,3]/la.norm(Y[:,3])
     
    # Finally, we return the result:
    return Y

# This function uses the Gram-schmidt process to calculate the dimension
# spanned by a list of vectors.
# Since each vector is normalised to one, or is zero,
# the sum of all the norms will be the dimension.
def dimensions(X) :
    return np.sum(la.norm(gsprocess(X), axis = 0))

## Test the code 

In [78]:
V = np.array([[5,0,3,4],
              [2,1,9,2],
              [-5,2,8,3],
              [2,6,2,1]], dtype=np.float_)
Vgs = gsprocess(V)
Vgs


array([[ 0.65653216, -0.05403511,  0.32111719,  0.68038921],
       [ 0.26261287,  0.13508778,  0.74723182, -0.59534056],
       [-0.65653216,  0.36743876,  0.50311276,  0.42524326],
       [ 0.26261287,  0.9185969 , -0.29224289, -0.04252433]])

In [79]:
#Testing whether resultant matrix is orthogonal or not
# if both inverse ond Transpose both are equal then, resultant Matrix has
#Orthogonal Vectors
inverse = la.inv(Vgs)
Transpose = np.transpose(Vgs)

In [80]:
inverse

array([[ 0.65653216,  0.26261287, -0.65653216,  0.26261287],
       [-0.05403511,  0.13508778,  0.36743876,  0.9185969 ],
       [ 0.32111719,  0.74723182,  0.50311276, -0.29224289],
       [ 0.68038921, -0.59534056,  0.42524326, -0.04252433]])

In [81]:
Transpose

array([[ 0.65653216,  0.26261287, -0.65653216,  0.26261287],
       [-0.05403511,  0.13508778,  0.36743876,  0.9185969 ],
       [ 0.32111719,  0.74723182,  0.50311276, -0.29224289],
       [ 0.68038921, -0.59534056,  0.42524326, -0.04252433]])

In [82]:
#Finding the dimensions of the resultant Orthogonal Matrix
dimensions(V)

4.0

## Assignment

#### Repeat the process by executing for new Matrix
1. Generate orthogonal basis vector set
2. Find Transpose and Inverse -  Verify basis vector set is orthogonal

In [7]:
A = np.array([[5,0,3,4],
              [2,1,9,2],
              [-5,2,8,3],
              [2,6,2,1]], dtype=np.float_)

In [8]:
## Write code and complete the Assignment

# Part 2 :
## Write the general form to make the function to generate orthogonal basis vector set for any number of column set of input matrix

In [124]:
#Lets take a very small number and if the magnitude value goes less than that, we will equate to zero,
#Because , Magnitude cannot be negetive
verySmallNumber = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001
def gsprocess2(X) :
    Y = np.array(X, dtype=np.float_)
    Y[:,0] = Y[:,0]/la.norm(Y[:,0])
    for i in range(1,Y.shape[1]):    
        for j in range (0,i):
            Y[:,i] = Y[:,i] - Y[:,i]@ Y[:,j] * Y[:,j]        
        if la.norm(Y[:, i]) > verySmallNumber :
            Y[:,i] = Y[:,i]/la.norm(Y[:,i]) #Finally deviding by its magnitude
        else:
            Y[:, i] = np.zeros_like(Y[:, i])
    return Y

def dimensions2(X) :
     return np.sum(la.norm(gsprocess2(X), axis = 0))

In [125]:
A = np.array([[5,0,3,4],
              [2,1,9,2],
              [-5,2,8,3],
              [2,6,2,1]], dtype=np.float_)
Ags = gsprocess2(A)
Ags


array([[ 0.65653216, -0.05403511,  0.32111719,  0.68038921],
       [ 0.26261287,  0.13508778,  0.74723182, -0.59534056],
       [-0.65653216,  0.36743876,  0.50311276,  0.42524326],
       [ 0.26261287,  0.9185969 , -0.29224289, -0.04252433]])

In [126]:
## Testing for Non Square Matrix
B = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
Bgs = gsprocess2(B)
Bgs

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [127]:
#Testing whether resultant matrix is orthogonal or not
# if both inverse ond Transpose both are equal then, resultant Matrix has
#Orthogonal Vectors
Transpose2 = np.transpose(Bgs)
Transpose2 

array([[ 0.23643312,  0.15762208,  0.15762208,  0.94573249],
       [ 0.18771349,  0.74769023,  0.57790444, -0.26786082],
       [ 0.22132104, -0.64395812,  0.72904263, -0.06951101]])

In [128]:
#No Inverse for non square matrix

In [129]:
dimensions2(B)

3.0

In [130]:
#Testing when one vector is linear dependent of another
C = np.array([[4,4,2],
              [0,-2,-5],
              [8,8,4]], dtype=np.float_)
gsprocess2(C)

array([[ 0.4472136 ,  0.        ,  0.        ],
       [ 0.        , -1.        ,  0.        ],
       [ 0.89442719,  0.        ,  0.        ]])

In [132]:
#Results in losing the space
dimensions2(C)

2.0

## Assignment

In [ ]:
B = np.array([[4,3,4,6],
              [1,2,2,2],
              [-2,4,2,1],
              [-1,7,5,3]], dtype=np.float_)