In [3]:
import numpy as np 
x = [1,2,3]
vector = np.array(x)
vector

array([1, 2, 3])

In [4]:
vector.ndim 

1

In [6]:
vector.shape

(3,)

# Arithmetic Operations on Vectors 

In [8]:
a = np.random.randint(10, 50, size=5) 
b = np.random.randint(25, 75, size=5) 
print(a)
print(b)
c=a+b 
print(c)

[21 11 20 34 36]
[59 63 51 69 58]
[ 80  74  71 103  94]


In [9]:
a = np.random.randint(10, 50, size=5) 
b = np.random.randint(25, 75, size=5) 
print(a)
print(b)
c=a-b 
print("Difference = ",c)

[13 45 49 39 31]
[25 53 58 61 48]
Difference =  [-12  -8  -9 -22 -17]


In [10]:
a = np.random.randint(10, 50, size=5) 
b = np.random.randint(25, 75, size=5) 
print(a)
print(b)
c=a*b 
print("Multiplication = ",c)

[25 24 32 20 14]
[34 29 62 63 48]
Multiplication =  [ 850  696 1984 1260  672]


In [11]:
a = np.random.randint(10, 50, size=5) 
b = np.random.randint(25, 75, size=5) 
print(a)
print(b)
c=a/b 
print("Division = ",c)

[24 44 43 42 30]
[53 40 47 43 61]
Division =  [0.45283019 1.1        0.91489362 0.97674419 0.49180328]


# Dot Product 

In [12]:
a = np.random.randint(10, 50, size=5) 
b = np.random.randint(25, 75, size=5) 
print(a)
print(b)


[43 49 19 13 20]
[25 49 57 63 52]


In [13]:
vector_dot = a.dot(b)
vector_dot 

6418

In [16]:
import numpy as np  
x = np.arange(5,10)
y = np.arange(5)
print(x)
print(y)
vector_dot = x.dot(y)
print("dot product", vector_dot) 

[5 6 7 8 9]
[0 1 2 3 4]
dot product 80


# Vector Scalar Multiplication 


In [17]:
x = np.arange(5,10) 


In [18]:
vs = 3*x 
print("Vector Scalar Multiplication is :", vs)

Vector Scalar Multiplication is : [15 18 21 24 27]


In [19]:
x

array([5, 6, 7, 8, 9])